# Site settings
title: Swifter
description: A clean minimal Theme for Jekyll
email: 
baseurl: /swift
url: "http://electrocute.github.io" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png

#feed
feedburner_username: 
#twitter
twitter_username: ericamoncsko
github_username:  electrocute

#linkedin
linkedin_username: 

#google analytics
google_analytics_id:
#gplus
gplus_username: 

#fb_username
fb_username: 

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: 
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  erica:
    display_name: Erica Young
    #email: 
    #fb: pranav.tayberrycreative
    #linkedin: pranavrajs
    twitter: ericamoncsko
    github: electrocute
